### ISSUE TITLE
Toggle for the music

### ISSUE THREAD

**Issue by YnwLNE** [JunyDeveloper/GamblingModLethalCompany#1]
Great mod but would like the ability to lower or disable the music, it isn't fitting to the machine imo

**Comment by JunyDeveloper** [comment]
I can add a configuration to disable the music :). I tend lean more towards non-immersive and meme kind of content which is why the music and SFX isn't quite fitting!

**Comment by JunyDeveloper** [comment]
Just pushed out the changes and it should be available once you update to 1.0.4! 

You should be able to:
- Disable music
- Change music volume
