### ISSUE TITLE
Text Font and hand icon

### ISSUE THREAD

**Issue by anon-cfg** [JunyDeveloper/GamblingModLethalCompany#15]
Would it be possible to get a config option to use the normal lethal company text font on the gambling machine? The current text font feels a bit out of place. Also the normal hand icon when interacting. To better fit in with the game's visual aesthetic.

Love the mod, thanks!
![image](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/155375310/1188a5d5-d019-454f-a3d1-d07d8ad37d73)
![image (1)](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/155375310/0350c5ad-c1d4-4e9a-a0a6-465569653276)

**Comment by JunyDeveloper** [comment]
Great suggestion! I'll take a look at this next weekend once I get back from vacation. I'll just need to dig around to see what icon and font style the game is using :)

**Comment by MGJerry** [comment]
If this helps, Zeekerss said it was 3270font ([src](https://twitter.com/ZeekerssRBLX/status/1728511390821024237)), dunno about icons tho

**Comment by JunyDeveloper** [comment]
Gonna start looking into this feature. Thanks for checking for the font @MGJerry !

**Comment by JunyDeveloper** [comment]
I updated the text and font which will be in version 1.2.3+! 

I had some problems getting the hand icon to show, so I made another issue to get that working in another update 👍 
https://github.com/JunyDeveloper/GamblingModLethalCompany/issues/33
