### ISSUE TITLE
config problem

### ISSUE THREAD

**Issue by chasedpg** [JunyDeveloper/GamblingModLethalCompany#16]
i cant find out how to config the gambling chance and multiplier. could u describe exactly how to change it?

**Comment by JunyDeveloper** [comment]
Are you using a mod manager like "Thunderstore" by any chance? If so you can hit "Edit Config" and click on `Junypai.GamblersMod.cfg`. See this screenshot:
![Ex](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/5916453/02f28b7c-e4e3-44bd-9c8f-1fda8f5b6600)

If you're not using any mod managers, you can edit it here:
`Steam\steamapps\common\Lethal Company\BepInEx\config\Junypai.GamblersMod.cfg`
