### ISSUE TITLE
Spamming = Rich = Broken Game

### ISSUE THREAD

**Issue by PenguCCN** [JunyDeveloper/GamblingModLethalCompany#17]
If multiple people spam to gamble fast enough it breaks the system and starts giving out high prices (up to around 80k per scrap)

**Comment by JunyDeveloper** [comment]
Ooof. These gambling addicts getting out of control... Thanks for letting me know! I'll take a look

**Comment by JunyDeveloper** [comment]
Made some changes for Version 1.1.1+! If you update to the latest version it should hopefully alleviate some of this issue.
