### ISSUE TITLE
Limit need

### ISSUE THREAD

**Issue by yuukaguya** [JunyDeveloper/GamblingModLethalCompany#20]
Players like to spend time at the gambling machines in multiplayers game,it's a bit of a waste of time. Could you add some restrictions,just like limiting the number of gambling or the maximum number of scrap each player can gamble?

**Comment by JunyDeveloper** [comment]
Great idea! Next week I’ll add a configurable option to be able to enable a limit and also be able to set that limit number 👍

**Comment by germ4nic** [comment]
> it's a bit of a waste of time. Could you add some restrictions,just like limiting the number of gambling or the maximum number of scrap each player can gamble?
losers mentality
![quots](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/128669664/12781f46-db03-4bff-ab99-f072e7adbe5d)

**Comment by germ4nic** [comment]
> Players like to spend time at the gambling machines in multiplayers game,it's a bit of a waste of time. Could you add some restrictions,just like limiting the number of gambling or the maximum number of scrap each player can gamble?

losers mentality
![quots](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/128669664/a7317454-628f-4994-8b47-0e9f24c957e0)

**Comment by MGJerry** [comment]
> > Players like to spend time at the gambling machines in multiplayers game,it's a bit of a waste of time. Could you add some restrictions,just like limiting the number of gambling or the maximum number of scrap each player can gamble?
> 
> losers mentality ![quots](https://private-user-images.githubusercontent.com/128669664/294660229-a7317454-628f-4994-8b47-0e9f24c957e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODkyOTMsIm5iZiI6MTcwNDc4ODk5MywicGF0aCI6Ii8xMjg2Njk2NjQvMjk0NjYwMjI5LWE3MzE3NDU0LTYyOGYtNDk5NC04YjQ3LTBlOWYyNGM5NTdlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwODI5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTIwY2UyYjM4NDdkYTEzYmE2NTE3MjM0NTlkMDkyM2FmMThmZWI5YjVhOWM3NjU0YjE0ODk5NGJlZTVlNzQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IJZAGJydpoRZLNn4-RBodz1oFIgDMDNt-ibnSvtLs7g)

TRUUEEEEE brother, they don't understand the amount of stonks we are making.
99% of gamblers quit before hitting their big wins anyways

**Comment by LJL-xyck** [comment]
For some reasons, I dont know. when using this mod, I can't interact the machine, I don't know what the bug is.

**Comment by JunyDeveloper** [comment]
@LJL-xyck Do you know what you have your "Interact" key set to for your key-binds?

**Comment by JunyDeveloper** [comment]
@yuukaguya If you update to version 1.3.4+ you should have a new configurable field to limit the usage for a gambling machine :)
