### ISSUE TITLE
Machine is a spaceship

### ISSUE THREAD

**Issue by PenguCCN** [JunyDeveloper/GamblingModLethalCompany#21]
As seen below, the gambling machine persists outside the ship. Visuals are possible thanks to LethalExpansion and OpenShipDoor. Previously we could hear the music of the machine after leaving the company but didn't realize the actual machine was very much following us.

![image](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/86432003/9e872396-3565-429d-af37-e5045f86af51)

**Comment by JunyDeveloper** [comment]
Was this a ship during a moon landing or was it in "in orbit".

**Comment by MGJerry** [comment]
huh, so this is why sometimes I still hear it after we leave the company

> Was this a ship during a moon landing or was it in "in orbit".
"in orbit", after leaving the company building. For me it rarely happens tho, like a 1% chance.

**Comment by PenguCCN** [comment]
> Was this a ship during a moon landing or was it in "in orbit".

Orbit, every single time

**Comment by JunyDeveloper** [comment]
If you update to version 1.3.4+ this should hopefully be fixed :)
