### ISSUE TITLE
2 GamblingMachine

### ISSUE THREAD

**Issue by ginsetsu-a** [JunyDeveloper/GamblingModLethalCompany#22]
hello, I am japanese gambler. 
I don't speak good English. So,sorry if my text is hard to read.
I always Play with my gamble frends.
So I want second GamblingMachine.

thank you

**Comment by JunyDeveloper** [comment]
Hello :)! I'll look into adding an feature to be able to add more gambling machines

**Comment by JunyDeveloper** [comment]
If you update to version 1.3.4+ you should have a new configurable field to add more gambling machines :)

**Comment by ginsetsu-a** [comment]
Thank you for responding to my request <3
