### ISSUE TITLE
 Add more gambling machines

### ISSUE THREAD

**Issue by germ4nic** [JunyDeveloper/GamblingModLethalCompany#23]
Hola,

Me and my 3 other friends would really like to all gamble at the same time. This was our last run and safe to say, we definitely don't have a problem. I just would like 3 more machines and as well possibly rolling all of them with the same piece of scrap so we cam gamble 4x as fast. Thanks.
![image](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/128669664/bb4bf276-e82e-414f-9d99-d1d11003ab7f)
![blaifs](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/128669664/639505f9-febb-471c-bad9-074ef6008833)
![quots](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/128669664/6d106aa0-7e97-444a-8044-abadfe7662fd)
![blijgm](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/128669664/51b2549b-088a-4a1f-b47f-1499c7ffeaf6)

**Comment by JunyDeveloper** [comment]
Hello! I also saw another similar request for this so I'll look into it 👍

**Comment by JunyDeveloper** [comment]
If you update to version 1.3.4+ you should have a new configurable field to add more gambling machines :)
