### ISSUE TITLE
WE NEED MORE SLOTS

### ISSUE THREAD

**Issue by Sm3ltyx** [JunyDeveloper/GamblingModLethalCompany#25]
also real money exchange

**Comment by JunyDeveloper** [comment]
Hello! Will look into adding more machines. You can also update to 1.1.3+ to be able to reduce the cool-down of the machine :).

**Comment by MGJerry** [comment]
also add play-to-earn mechanics

_wait a minute... ain't that just **playing the actual game**?_

jokes aside, we need this feature bad, ain't no way ma bois spending 10-15 mins looting for scraps and half an hour gambling :'(
(was a hour before I put the cooldown to 1 second)

**Comment by JunyDeveloper** [comment]
If you update to version 1.3.4+ you should have a new configurable field to add more gambling machines :)
