### ISSUE TITLE
Multiplier bug

### ISSUE THREAD

**Issue by Qugar** [JunyDeveloper/GamblingModLethalCompany#26]
Hi,

I have a problem with the multipliers. If I set them like this

![Before](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/8191849/432efbb7-e957-4f6a-9fe0-3882431a2061)

and then start the game, then the mod changes the multipliers back to

![After](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/8191849/fa362175-a9e0-439d-a9e9-2a9edffffb1c)

Am I doing something wrong or is this intentional?

**Comment by JunyDeveloper** [comment]
Ah this is because I need to make it so those fields can be decimals. Right now they can only be whole numbers with the exception of the "HalveMultiplier" field. I'll update this so they can be decimals!

**Comment by JunyDeveloper** [comment]
Hello! If you update to 1.1.3+ you should be able to change those numbers to decimals now :)

**Comment by Qugar** [comment]
Runs like a charm now. Thank you =)
