### ISSUE TITLE
Sold item scrap value

### ISSUE THREAD

**Issue by marlochristian** [JunyDeveloper/GamblingModLethalCompany#27]
Gambled a key from 3 to 4k value and when it was sold, it was counted as 0 scrap value.
![20240107094904_1](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/60989409/da3a6cf3-c99c-4c31-8240-1113c2e48595)

![20240107095019_1](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/60989409/1b3d541c-0d55-4728-8b4b-4dbed45bde2b)

**Comment by Qugar** [comment]
Keys have never been worth anything, that's a flaw in the game itself. The game shows a value of 3 but when you sell them you always get 0.
