### ISSUE TITLE
how to configure

### ISSUE THREAD

**Issue by Barkie12** [JunyDeveloper/GamblingModLethalCompany#36]
how to configure the changes etc?

**Comment by pazz1n** [comment]
> how to configure the changes etc?

Lethal Company ---> BepInEx ---> config ---> GamblersMod.cfg

**Comment by JunyDeveloper** [comment]
Are you using a mod manager like "Thunderstore" by any chance? If so you can hit "Edit Config" and click on `Junypai.GamblersMod.cfg`. See this screenshot:
![Ex](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/5916453/02f28b7c-e4e3-44bd-9c8f-1fda8f5b6600)

If you're not using any mod managers, you can edit it here:
`Steam\steamapps\common\Lethal Company\BepInEx\config\Junypai.GamblersMod.cfg`
