### ISSUE TITLE
Use Lethal Company's credit icon instead of dollar sign

### ISSUE THREAD

**Issue by Ashesh3** [JunyDeveloper/GamblingModLethalCompany#5]
https://github.com/JunyDeveloper/GamblingModLethalCompany/blob/25972a66e9ee9a21e11c7b61b758f4a71b324fd4/GamblersMod/Player/PlayerControllerCustom.cs#L68C94-L68C95

To make the mod more in line with the existing system of representing credits, we should have the credits icon ▊ instead of the `$` sign, as nowhere in the game a dollar is used, and it's more immersive and realistic if instead the credit icon used by the company is shown instead.

![image](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/3626859/8c1983ae-302d-4703-aa30-f32ede49be63)

Specifically:

![image](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/3626859/078b2bec-ea60-4410-b0fb-89688782cba6)
![image](https://github.com/JunyDeveloper/GamblingModLethalCompany/assets/3626859/fa19ce8f-fc0b-4c22-b445-9926966a13ad)

The closest Unicode I could find is this: ▊

**Comment by JunyDeveloper** [comment]
Will make this update! Thanks for sending the uni-code too!

**Comment by JunyDeveloper** [comment]
Updated! This will be released in version 1.0.6+
