### ISSUE TITLE
Change keybind

### ISSUE THREAD

**Issue by anon-cfg** [JunyDeveloper/GamblingModLethalCompany#6]
Change the keybind for using the gambling machine to the users interact key, for cases where the user has rebinded their interact key to something other than E.

**Comment by JunyDeveloper** [comment]
So right now the text on screen is just hard-coded to show "E", but the game will use the interact key-bind the player is set to. I'll make an update so that the "E" is no longer hard-coded and will show the player's interact key 👍

**Comment by JunyDeveloper** [comment]
This will be in the 1.0.7 version once you upgrade!
